import os,time
print('Welcome to arch linux installer!')
print('This installs arch linux over your system.')
print('And doesnt damage your system!')
print('Do you want to install it?')
a = input('[y/n]: ')
if a.lower()[0] == 'n':
  quit()
print('Downloading arch linux.')
os.system('wget https://archive.archlinux.org/iso/2020.04.01/archlinux-bootstrap-2020.04.01-x86_64.tar.gz')
print('Unzipping rootfs. This may take some time.')
time.sleep(0.5)
os.system('tar -xvf archlinux-bootstrap-2020.04.01-x86_64.tar.gz')
print('Removing tarball')
os.system('rm archlinux-bootstrap-2020.04.01-x86_64.tar.gz')
print('Updating pacman database')
os.system('proot -0 -w / -r root.x86_64 "pacman -Syyu"')
print('Done! Running arch')
os.system('clear')
print('Welcome to arch linux!')
print('Note: some of things may not work')
os.system('proot -0 -w / -r root.x86_64 bash')
